// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Group: typeof import('./src/components/group.vue')['default']
    Invite: typeof import('./src/components/Invite.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NewChore: typeof import('./src/components/NewChore.vue')['default']
    Notification: typeof import('./src/components/notification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/test.vue')['default']
  }
}

export {}
