// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/Alert.vue')['default']
    ChoreCycle: typeof import('./src/components/ChoreCycle.vue')['default']
    Invites: typeof import('./src/components/invites.vue')['default']
    MyGroups: typeof import('./src/components/MyGroups.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NewChore: typeof import('./src/components/NewChore.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
