[build.environment]
    NPM_FLAGS = "--version"
    NODE_VERSION = "17.6.0"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[build]
    publish = "dist"
    command = "npm i && npm run build"

[[headers]]
    for = "/manifest.webmanifest"
    [headers.values]
      Content-Type = "application/manifest+json"