// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Alert: typeof import('./components/Alert.vue')['default']
    Badge: typeof import('./components/Badge.vue')['default']
    Bottombar: typeof import('./components/Bottombar.vue')['default']
    ChoreCycle: typeof import('./components/ChoreCycle.vue')['default']
    Invites: typeof import('./components/Invites.vue')['default']
    MyGroups: typeof import('./components/MyGroups.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    NewChore: typeof import('./components/NewChore.vue')['default']
    Panel: typeof import('./components/Panel.vue')['default']
    QuickBox: typeof import('./components/QuickBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
